// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjqgolpphxeckahqlnid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcWdvbHBwaHhlY2thaHFsbmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NTA3MDgsImV4cCI6MjA0OTIyNjcwOH0.Z1xzwNVKC68RpltNx_Q8GxQOQlZnxuFMcoEBecdAly0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);